#ifndef KEYMAP_H
#define KEYMAP_H
#include <linux/input.h>
#define KEY_MAX_CODE 0x2ff

const char *key_code_names[KEY_MAX_CODE + 1] = {
    [KEY_ESC] = "ESC",
    [KEY_1] = "1",
    [KEY_2] = "2",
    [KEY_3] = "3",
    [KEY_4] = "4",
    [KEY_5] = "5",
    [KEY_6] = "6",
    [KEY_7] = "7",
    [KEY_8] = "8",
    [KEY_9] = "9",
    [KEY_0] = "0",
    [KEY_A] = "A",
    [KEY_B] = "B",
    [KEY_C] = "C",
    [KEY_D] = "D",
    [KEY_E] = "E",
    [KEY_F] = "F",
    [KEY_G] = "G",
    [KEY_H] = "H",
    [KEY_I] = "I",
    [KEY_J] = "J",
    [KEY_K] = "K",
    [KEY_L] = "L",
    [KEY_M] = "M",
    [KEY_N] = "N",
    [KEY_O] = "O",
    [KEY_P] = "P",
    [KEY_Q] = "Q",
    [KEY_R] = "R",
    [KEY_S] = "S",
    [KEY_T] = "T",
    [KEY_U] = "U",
    [KEY_V] = "V",
    [KEY_W] = "W",
    [KEY_X] = "X",
    [KEY_Y] = "Y",
    [KEY_Z] = "Z",
    [KEY_ENTER] = "ENTER",
    [KEY_SPACE] = "SPACE",
    [KEY_BACKSPACE] = "BACKSPACE",
    [KEY_LEFTSHIFT] = "LEFTSHIFT",
    [KEY_RIGHTSHIFT] = "RIGHTSHIFT",
    [KEY_LEFTCTRL] = "LEFTCTRL",
    [KEY_RIGHTCTRL] = "RIGHTCTRL",
    [KEY_LEFTALT] = "LEFTALT",
    [KEY_RIGHTALT] = "RIGHTALT",
    [KEY_TAB] = "TAB",
    [KEY_CAPSLOCK] = "CAPSLOCK",
    [KEY_UP] = "UP",
    [KEY_DOWN] = "DOWN",
    [KEY_LEFT] = "LEFT",
    [KEY_RIGHT] = "RIGHT"};

#endif